version: "3.8"

services:
  postgres:
    image: postgres
    container_name: emailpackage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=emaildb
    ports:
      - "5432:5432"
